//로그인
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
//로그아웃
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCESS = "LOGOUT_SUCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
//회원가입
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCESS = "REGISTER_SUCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
//유저로딩
export const USER_LOADING_REQUEST = "USER_LOADING_REQUEST";
export const USER_LOADING_SUCESS = "USER_LOADING_SUCESS";
export const USER_LOADING_FAIL = "USER_LOADING_FAIL";
//에러
export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST";
export const CLEAR_ERROR_SUCESS = "CLEAR_ERROR_SUCESS";
export const CLEAR_ERROR_FAIL = "CLEAR_ERROR_FAIL";
//게시글작성
export const POST_WRITE_REQUEST = "POST_WRITE_REQUEST";
export const POST_WRITE_SUCESS = "POST_WRITE_SUCESS";
export const POST_WRITE_FAIL = "POST_WRITE_FAIL";
//게시글로딩
export const POST_LOADING_REQUEST = "POST_LOADING_REQUEST";
export const POST_LOADING_SUCESS = "POST_LOADING_SUCESS";
export const POST_LOADING_FAIL = "POST_LOADING_FAIL";
