//로그인
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
//로그아웃
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCESS = "LOGOUT_SUCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
//회원가입
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCESS = "REGISTER_SUCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
//유저로딩
export const USER_LOADING_REQUEST = "USER_LOADING_REQUEST";
export const USER_LOADING_SUCESS = "USER_LOADING_SUCESS";
export const USER_LOADING_FAIL = "USER_LOADING_FAIL";
//에러
export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST";
export const CLEAR_ERROR_SUCESS = "CLEAR_ERROR_SUCESS";
export const CLEAR_ERROR_FAIL = "CLEAR_ERROR_FAIL";
//게시글작성
export const POST_WRITE_REQUEST = "POST_WRITE_REQUEST";
export const POST_WRITE_SUCESS = "POST_WRITE_SUCESS";
export const POST_WRITE_FAIL = "POST_WRITE_FAIL";
//게시글로딩
export const POST_LOADING_REQUEST = "POST_LOADING_REQUEST";
export const POST_LOADING_SUCESS = "POST_LOADING_SUCESS";
export const POST_LOADING_FAIL = "POST_LOADING_FAIL";
//게시글업로드
export const POST_UPLOAD_REQUEST = "POST_UPLOAD_REQUEST";
export const POST_UPLOAD_SUCESS = "POST_UPLOAD_SUCESS";
export const POST_UPLOAD_FAIL = "POST_UPLOAD_FAIL";
//게시글상세페이지
export const POST_DETAIL_REQUEST = "POST_DETAIL_REQUEST";
export const POST_DETAIL_SUCESS = "POST_DETAIL_SUCESS";
export const POST_DETAIL_FAIL = "POST_DETAIL_FAIL";
//게시글삭제
export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_SUCESS = "POST_DELETE_SUCESS";
export const POST_DELETE_FAIL = "POST_DELETE_FAIL";
//댓글로딩
export const COMMENT_LOADING_REQUEST = "COMMENT_LOADING_REQUEST";
export const COMMENT_LOADING_SUCESS = "COMMENT_LOADING_SUCESS";
export const COMMENT_LOADING_FAIL = "COMMENT_LOADING_FAIL";
//댓글업로드
export const COMMENT_UPLOAD_REQUEST = "COMMENT_UPLOAD_REQUEST";
export const COMMENT_UPLOAD_SUCESS = "COMMENT_UPLOAD_SUCESS";
export const COMMENT_UPLOAD_FAIL = "COMMENT_UPLOAD_FAIL";
//게시글수정로딩
export const POST_EDIT_LOADING_REQUEST = "POST_EDIT_LOADING_REQUEST";
export const POST_EDIT_LOADING_SUCESS = "POST_EDIT_LOADING_SUCESS";
export const POST_EDIT_LOADING_FAIL = "POST_EDIT_LOADING_FAIL";
//게시글수정
export const POST_EDIT_UPLOAD_REQUEST = "POST_EDIT_UPLOAD_REQUEST";
export const POST_EDIT_UPLOAD_SUCESS = "POST_EDIT_UPLOAD_SUCESS";
export const POST_EDIT_UPLOAD_FAIL = "POST_EDIT_UPLOAD_FAIL";
//카테고라 찾기
export const CATEGORY_FIND_REQUEST = "CATEGORY_FIND_REQUEST";
export const CATEGORY_FIND_SUCESS = "CATEGORY_FIND_SUCESS";
export const CATEGORY_FIND_FAIL = "CATEGORY_FIND_FAIL";
//검색
export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCESS = "SEARCH_SUCESS";
export const SEARCH_FAIL = "SEARCH_FAIL";
//비밀번호 수정
export const PASSWORD_EDIT_REQUEST = "PASSWORD_EDIT_REQUEST";
export const PASSWORD_EDIT_SUCESS = "PASSWORD_EDIT_SUCESS";
export const PASSWORD_EDIT_FAIL = "PASSWORD_EDIT_FAIL";
//게스글 즐겨찾기
export const POST_BOOKMARK_REQUEST = "POST_BOOKMARK_REQUEST";
export const POST_BOOKMARK_SUCESS = "POST_BOOKMARK_SUCESS";
export const POST_BOOKMARK_FAIL = "POST_BOOKMARKE_FAIL";
